### ISSUE TITLE
No Lan connection  After battery module change to the new LFP batteries in the Senec Home V3 Hybrid

### ISSUE THREAD

**Issue by Dainara82** [marq24/ha-senec-v3#111]
### With which version of the integration you have an issue?

SENEC.Home V3 hybrid/SENEC.Home V3 hybrid duo/SENEC.Home V2.1 (or older) 

### Multiple Systems Environment?

- [ ] I have multiple SENEC Systems (master/slave configuration)

### Checklist

- [X] I have installed the **latest** release (or BETA) version of the integration and home assistant.
- [X] I have prepared DEBUG log output (for technical issues) | In most of the cases of a technical error/issue I would have the need to ask for DEBUG log output of the integration. There is a short [tutorial/guide 'How to provide DEBUG log' here](https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md)
- [X] I understand the SHIT-__IN__ - SHIT-__OUT__ principle (in case of implausible data) | It will happen, that the data that is displayed by this integration does not make much sense (to you) - Of course this could be always the case, that something in this integration has been messed up - but so far - in all reported issues the root cause of implausible data was/is, that the SENEC.Home device itself already provided this data
- [X] I confirm it's really an issue | In the case that you want to understand the functionality of a certain feature/sensor Please be so kind and make use if the discussion feature of this repo (and do not create an issue) - TIA

### Add a description

I Found the same  problem in OpenHab, there it takes an fix, maybe you can fix it too
i can't integrate Senec.Home  couse no LAN connection, but the Lan connection work int the browser

https://github.com/openhab/openhab-addons/issues/17298

**Comment by marq24** [comment]
The latest release of this integration should with "switched" LFP batteries (number of battery modules typically will be reduced) - my Hybrid Duo batteries have been replaced 3 weeks ago - and also the system have been updated to:

REVISION MCU: 0831
REVISION MCU-BL: 2307
REVISION NPU-REGS: 03
REVISION NPU-IMAGE: 2408
REVISION GUI: 0969

Integration is working here "rock solid" (it's still a SENEC device)... The linked openhab issue does not help here ...

Please make sure you have the latest integration version installed -> https://github.com/marq24/ha-senec-v3/releases/tag/2024.11.2 and if there is still an issue: **provide debug log output** (even when there is "no LAN connection" - this would cause a error visible in the logs)

**Comment by marq24** [comment]
@Dainara82 any additional Feedback? - Issue solved?
