### ISSUE TITLE
Wrong unit in senec_house_power

### ISSUE THREAD

**Issue by MrIcemanLE** [marq24/ha-senec-v3#13]
Hi!

I noticed that the entity sensor.senec_house_power has the wrong unit. In my case I get around 800kW. Thats way to much. I think it has to be 800W. Unfortunately i changed the entity_id back to the old ones so all my dashboards continue working. The entity shows the current power the "house" is using.

![image](https://github.com/marq24/ha-senec-v3/assets/6569956/88198713-4ce3-4bdd-aadf-78f979f30f68)

**Comment by marq24** [comment]
I can confirm, that `sensor.senec_house_power` should/is WATT
![image](https://github.com/marq24/ha-senec-v3/assets/8012359/deef1588-c9f9-4e1b-ac0d-93f9fe4ceb2f)

also code wise it's configured as WATT
https://github.com/marq24/ha-senec-v3/blob/5aff26b31d3b82c43295583993add08510c671a1/custom_components/senec/const.py#L272

But it could be, that in your installation something is mixed up with the additional WEB-API Integration - where "House Power" is measured in KILO_WATTS ?! see `sensor.senec_webapi_consumption_now` 
![image](https://github.com/marq24/ha-senec-v3/assets/8012359/5d38d227-12a5-49de-a48b-0550ea7c923c)
But this WebAPI Sensor should have a different Entity Name/ID?!

**Comment by io-debug** [comment]
Hi, I can also confirm that the sensor is configured correctly (in the code as well as in Home Assistant) in WATT.
@MrIcemanLE do you still experience this issue?

**Comment by MrIcemanLE** [comment]
So maybe something mixed up due to the "old" integration that stoped working some days ago. As I said I reused the old entitiy IDs to keep the energy dashboard working.

In my case both entities are showing Kilowatts. Any Idea how I can fix that? Can't change the unit manually. Maybe I should try to reinstall the integration

<img width="1039" alt="House Power Entities" src="https://github.com/marq24/ha-senec-v3/assets/6569956/0361a5a0-d881-4bfa-9ecb-b7c488e525c6">

**Comment by marq24** [comment]
> As I said I reused the old entitiy IDs to keep the energy dashboard working.

I just can guess, that this is the root of the problem... currently you can not reuse the original sensor ids... For the EnergyDashboard just add the new ones... and do not delete the (currently) not feeded ones... This will give you the best possible backward compatibility... We all dont know if the statistic data will return in the lala.cgi...

**Comment by bobthebuilder4711** [comment]
> Any Idea how I can fix that?

I would try opening the settings of the sensor and simply changing the unit. Or does that lead to home assistant converting the data behind the scenes?
