### ISSUE TITLE
WebAPI request for consumption of today, yesterday and the days before

### ISSUE THREAD

**Issue by alexanderroese** [marq24/ha-senec-v3#16]
Good day, thank you for forking the repo and programming a solution. By moving the statistics values from the lala.cgi to the cloud, there are no longer sensors that return the daily consumption of today, yesterday and the days before. In the mein-senec portal there is a graph under which is displayed how much kwh was consumed on that particular day. Is it possible that you implement this in the web api?

**Comment by marq24** [comment]
Hi @alexanderroese...

you can easily get these values when using the Energy Dashboard  of your ha installation - or if there are any obligations to use this dashboard you can simply create Utility Meters (Verbrauchsmesser) in the frequency (hour, day, week, month, year) you find convenient...
