### ISSUE TITLE
[No Issue] Confirmed working with Senec Home v2.1 Li 5.0

### ISSUE THREAD

**Issue by guevara777** [marq24/ha-senec-v3#2]
Thank you for your great work! I´m happy with it.

I can confirm it´s working fine with my Senec Home v2.1 Li 5.0 without any issues.

After downloading your repository via HACS and restarting Home Assistant i was able to change my polling-speed to 5 seconds. All other sensors kept working (and also had their historical data). 

Great work!

**Comment by marq24** [comment]
Thanks for your feedback! I have to admit, that as V3 owner I can't make and judgment, if this higher polling interval could have any negative side effect... 

I just observed that the request frequency of the build in web frontend of my Senec is more or less constantly requesting the lala.cgi script - so my train of thought was, when the internal web frontend could do that - I could do the same from HA...
