### ISSUE TITLE
While Emergency Charge is running battery charge and discharge are 0

### ISSUE THREAD

**Issue by iot-sle** [marq24/ha-senec-v3#46]
seem that only those both values are not filled in. I attached a screenshot showing corrent charge currents for the cells and on right hand a screenshot of "solectrus" using lala.cgi too. Which is showing the correct battery charging power. On upper right corner you can see status is "Notladung" 
![grafik](https://github.com/marq24/ha-senec-v3/assets/74416643/c262ba84-f222-40fe-ab91-39f4a67f7a27)

**Comment by marq24** [comment]
I am sorry - but I actually do not understand, what you are trying to ask/say...

Can you please be so kind and describe the problem/issue in one sentence? - What is he current behavior - what is the expected behavior - what is causing the behavior? 

TIA

**Comment by iot-sle** [comment]
I took a short look at your code, by the way thank you for your great work, the problem is line

BAT_STATUS_CHARGE = {4, 5, 8, 10, 11, 12, 14, 43, 71}

my status is 33: Saftey charge

**Comment by marq24** [comment]
You are right - there had been multiple states that have been missing - 23, 24, 25, 33

THANKS for your report - a new build/version is just around the corner

**Comment by marq24** [comment]
https://github.com/marq24/ha-senec-v3/releases/tag/3.1.1
