### ISSUE TITLE
webapi has stopped updating

### ISSUE THREAD

**Issue by BMeyendriesch** [marq24/ha-senec-v3#49]
### Discussed in https://github.com/marq24/ha-senec-v3/discussions/48

<div type='discussions-op-text'>

<sup>Originally posted by **Disincentivato** December  5, 2023</sup>
Since this morning the webapi have no longer been updated. What could it be?
![Immagine 2023-12-05 163738](https://github.com/marq24/ha-senec-v3/assets/90531670/a291d8ac-4403-452d-9ba4-141d31e4186b)
</div>

**Comment by marq24** [comment]
let's keep the discussion in #48
