### ISSUE TITLE
Energiedashboard

### ISSUE THREAD

**Issue by SimonFuVo** [marq24/ha-senec-v3#5]
Hallo, bei mir werden vom Energiedashboard die einzelnen Entitäten nicht akzeptier. Muss ich hier selber etwas anpassen?

Ich habe Version 3.0.6-test-04.

Ansonsten vielen Dank für die bereitstellung der neuen Integration.

![Screenshot_20230904_101942_Home Assistant](https://github.com/marq24/ha-senec-v3/assets/131409325/ccb67466-62d5-445d-a3da-42f81ba14e6b)

**Comment by marq24** [comment]
That's the name of the sensor when using the V2.x/V3 Variant (polling lala.cgi) in your LAN) - when you use V4/WebAPI, then the sensor name is different:  `sensor.senec_webapi_gridexport_total` (when you use the default 'Name')

**Comment by SimonFuVo** [comment]
Name of sensor from v3 localy which not work is
sensor.senec_solar_generated_power

**Comment by marq24** [comment]
sorry - updated my initial reply

**Comment by SventeHof** [comment]
same Problem.. the following entitys are not queried and displayed:

- sensor.senec_grid_total_import
- sensor.senec_grid_total_export
- sensor.senec_solar_total_generated
- sensor.senec_battery_total_charged
- sensor.senec_battery_total_discharged

**Comment by marq24** [comment]
I have created for you gentlemen here https://github.com/marq24/ha-senec-v3/issues/4#issue-1873971875 a table showing old (lala.cgi incl. STATISTICS) and new sensor names (web-api based)

**Comment by marq24** [comment]
I hope with this additional info/issue #11 we can consider this as solved?

**Comment by SittingDuck52** [comment]
Additional Info:
[](https://www.home-assistant.io/docs/energy/electricity-grid/)
If you are unable to select your energy sensor in the grid consumption drop-down, make sure that its value is being recorded in the Recorder settings.
