### ISSUE TITLE
Cannot Configure Device

### ISSUE THREAD

**Issue by VolkerMal** [marq24/ha-senec-v3#50]
Hi,
installed Senec via HACS into HomeAssistant
by selecting Settings -> Devices -> Add Integration - selecting "SENEC" a dialog is popping up asking for:
a name
hostename of IP adress
Entering a name and the correct IP, it says: "No connection possible"
![Screenshot 2023-12-07 143705](https://github.com/marq24/ha-senec-v3/assets/108733895/20ee5b1e-b128-48da-acd5-ebb59fe3cb36)
See attached screenshot.

my Senec device is already upgraded and using https instead of http - but this cannot be selected/entered.

any idea what's wrong here ?
many thanks, Volker

**Comment by marq24** [comment]
Well - when you add the integration the first thing you should see/select is the device type - looks like that this is not the case for you...

![image](https://github.com/marq24/ha-senec-v3/assets/8012359/5f87f85b-9057-42ee-b34d-11674ff83fa0)

Could it be, that you are migrating from the https://github.com/mchwalisz/home-assistant-senec? If yes make sure that you follow the migration guide... [at least one HA restart is required...] - https://github.com/marq24/ha-senec-v3/issues/14

If all this is not the case, you need to enable the debug logging and share the output...
