### ISSUE TITLE
Total entities not increasing

### ISSUE THREAD

**Issue by loeffelpan** [marq24/ha-senec-v3#53]
Even after fix of #44 my energy dashboard does not look correct. The wrong values are gone, but the total sensors are not increasing anymore although there are values from now sensors.

![IMG_7176](https://github.com/marq24/ha-senec-v3/assets/34661317/593c3a16-c389-49da-bca6-047c26b41eb2)
![IMG_7175](https://github.com/marq24/ha-senec-v3/assets/34661317/46059d9b-6aac-4f0d-a418-6bbf228a078a)

**Comment by marq24** [comment]
please have a look here: https://github.com/marq24/ha-senec-v3/discussions/48

**Comment by loeffelpan** [comment]
Thanks. I did search in issues, but not in discussion.

**Comment by marq24** [comment]
NP :-) - so you have also the "thanks for nothing" message in your log - right?!
