### ISSUE TITLE
battery charge and discharge values are both 0 while battery is charging

### ISSUE THREAD

**Issue by iot-sle** [marq24/ha-senec-v3#55]
same as: `https://github.com/marq24/ha-senec-v3/issues/46` current version running 3.1.3
my status now is: 89 I guess it should be part of the BAT_STATUS_CHARGE too. Adding it seems to solve the problem.

**Comment by marq24** [comment]
mhhh - status 89 is "SPARE CAPACITY" (RESERVEKAPAZITÄT) - I hope this means, that the battery is currently not charging at all? [and also does not allow energy to be delivered from the battery to your house power network]... 

Currently the BAT_STATUS_CHARGE list "only" contains status's when the system is actually trying to add power to the battery... Just the "same" like 13 "BATTERY FULL" ?!...

So my understanding status 89 is some sort of similar to status 13 - do you agree or disagree?

**Comment by iot-sle** [comment]
As explained by email the behavior is different: As soon as the spare capacity is higher than the current battery load and there is production, the complete production is used to charge battery up to spare capicity level. Is there a reason why you are checking the status instead only taking in account the sign of "GUI_BAT_DATA_POWER"? May be with a little threshold of 10-50 W? After removing the status check in you code it seems to work as expected.

**Comment by marq24** [comment]
... could you please be so kind and just send me this mail your are talking about again? [I can't find it]...

The main reason behind this additional state check was/is, that I disliked the constant +/- 0-250 W values while the status of the system is not clearly in the charging/un-charging mode...

When the device is "below spare capacity" and there is production from PV, then I would expect, that the device is mode CHARGING (and not in SPARE CAPACITY)... 

I personally would consider the SPARE CAPACITY state more or less equal then the EMPTY state -> device will not provide any power to local network ... ?!

**Comment by marq24** [comment]
in any case with the latest release you have an additional option when configuring a already setup integration to disable the SYSTEM STATE check for the Sensors...

**Comment by iot-sle** [comment]
That's a good solution for me. Thank you.

**Comment by marq24** [comment]
so I assume we can close this? [I was hoping to get the eMail (again) you have mentioned] - and also I wanted to understand better the status 89 "SPARE CAPACITY"... since (just again) for me it would not make a lot of sense (but hey we are talking about Senec Software here) that when the system is set up to keep a min capacity, that in the case, that this limit is set, and the battery is charging or discharging that the system status would be "SPARE CAPACITY"... 

Again - IMHO "SPARE CAPACITY" is same as EMPTY or FULL status - just with a different battery level (Empty = 0%, Full = 100%, Space = X%) (X is specified by user)...

**Comment by iot-sle** [comment]
Seems that responses to the github emails don't reach you. I explained in that emails:

yes you can close it. I sent the email again. Seems it is blocked somewhere at Github.

Yes Senec Software is a nightmare in case of "design". Spare capacity mean no discharge of battery unless the backup power is used. ( which I never tested until now )
The behavior in case of solar generation and while charging battery is:

Status keeps on "Spare capacity" while batteries are charging. When battery level is lower than defined "spare capacity", battery charging has priority. Means all generated solar power is used for charging batteries. Consumption of the house is taken from grid! If you're interested in more details or personal email exchange perhaps in German language, we need to exchange email address.
