### ISSUE TITLE
Mein Senec Erzeugter PV-Strom does not work anymore

### ISSUE THREAD

**Issue by scottgoo** [marq24/ha-senec-v3#59]
Since 6th of december the Mein Senec Erzeugter PV-Strom sensor does not work anymore. 5th of december is the last day anything has been recorded.

The other sensors getting data from Mein Senec seem to work correctly.

**Comment by marq24** [comment]
could it be, that you are facing this issue here? https://github.com/marq24/ha-senec-v3/discussions/17 -> enable debug log and check if you get the "Thanks for..." lines...

**Comment by scottgoo** [comment]
Your damn right. Just turned on the debug log but as I see the values in senec webportal are lower than in HA. So it will fix itself.

Thank you very much fir the quick response!
