### ISSUE TITLE
Showing Sockets 

### ISSUE THREAD

**Issue by patricknitsch** [marq24/ha-senec-v3#63]
Hi,

i have a V2.1 with technical packet. So i have two configurable sockets.

Can you implement values for the sockets?

Many thanks

**Comment by marq24** [comment]
Good Morning Patrick,

well - IF the lala.cgi of your device will return data for these "sockets", then the answer is "yes I can" (but you have to provide way more details) -> e.g. share the output of the https://[YOUR-SENEC-IP]//vars.html 

If this "socket" data will be only available via the mein-senec.de - then the answer is also "yes" - but then the process is way more complicated... And since I do not have a 2.1 and also no "sockets" it will take quite long... If you are familiar with command line tools like CURL, then the process could be much faster... but still time consuming.

**Comment by patricknitsch** [comment]
Guten Morgen, 

habe gesehen, du kommst ja aus Deutschland. 

Ich habe dir ein Bild der Variablen für die Sockets angehängt.
![image](https://github.com/marq24/ha-senec-v3/assets/114565561/f5b4ecbc-767a-4f69-b61b-855b980034ea)

Wenn du weiter Informationen benötigst, unterstütze ich gerne. Mit ein paar Anweisungen kann ich auch mit Befehlen herausfinden, was du benötigst

**Comment by marq24** [comment]
ok - das sieht erstmal "einfach" umsetzbar aus... kannst Du mir das auch als TEXT (und nicht als Photo) zukommen -> ggf einfach speichern als HTML? - dann kann die Namen/Felder einfach COPY & PASTEN...

**Comment by marq24** [comment]
... sehe gerade ich hab' die auch ;-)

**Comment by patricknitsch** [comment]
Ich glaube mein Techniker hat mal gemeint, das is ne Option, die einfach nur frei geschaltet wird.

**Comment by marq24** [comment]
So since I have started to implemented them - in the meantime - what the heck this sockets are doing?!

**Comment by patricknitsch** [comment]
Das sind zwei potentialfreie Schaltkontakte, die bei PV Überschuss für eine gewisse Zeit schalten. Darüber läuft mein Boiler.

Unten siehst du ein Bild, wie das auf dem Webserver aussieht

![image](https://github.com/marq24/ha-senec-v3/assets/114565561/7ae9d512-1bea-4323-af08-7a8b67620488)

**Comment by marq24** [comment]
also SG-Ready

**Comment by patricknitsch** [comment]
Kannst du so ausdrücken. Nur dass ich keinen speziellen Heizstab habe, sondern nur einen normalen Speicher

**Comment by marq24** [comment]
Leider ist das mit den Schaltern nicht ganz so einfach für mich... Wenn Du auf eine der Checkboxen clickst [z.B. Permament an] und dann speichern sagst, dann macht die WEB Oberfläche ein POST request zu Deinem Speicher...

Diesen POST Payload müsste ich mal haben :-/

**Comment by patricknitsch** [comment]
Kann ich es irgendwie ausprobieren?

**Comment by marq24** [comment]
Ja Du müsstes das bei Dir lokal machen - gelichzeitig vom Browser die Developertools aufmachen und eben im Netzwerk-Tab "genau" den "POST" request rausuchen... dort findet man denn auch unter den Headern die "post-data"...

Wenn die diese ganzen Begriffe nichts sagen ist das völlig OK - das alles Entwickler-Gefasel (und für den normalen User schwer verdaulich)...

Wenn es aber in einer ERSTEN Version ausreichend ist, diese Felder zu LESEN (und eben nicht zu schreiben), dann hab' ich's erstmal ;-)

**Comment by patricknitsch** [comment]
Ich habe mal reingeschaut. Die post-data habe ich aber nicht gefunden. Hast du noch einen Tipp für mich, wo ich suchen kann?

<img width="1440" alt="image" src="https://github.com/marq24/ha-senec-v3/assets/114565561/75f1de01-bf38-4d32-94d3-898676d228e2">

**Comment by marq24** [comment]
Du musst auf den "Nutzlast" tab schauen...
![image](https://github.com/marq24/ha-senec-v3/assets/8012359/48b1eb53-c61c-4fa8-a272-8970b3c1eb10)

Wenn Du die Checkbox angeklickt hast und (ich vermute mal erst wenn Du den Save button drückst), dann gibt es leider auch nur einen weiteren Request an das lala.cgi... wonach wir suchen ist der Request, bei dem "ein Wert" auf irgendwas gesetzt ist... Hier in meinem Beispiel (und das ist leider das einzige was ich hier machen kann) wird das SAFE_CHARCE_FORCE auf `u8_01` gesetzt...

Normalerweise sind die Werte immer auf (leer) also `""` gesetzt - dann weiss der Senec "dazu sollen werte ausgeliefert werden"... Wenn Du also den Request findest, bei dem die Nutzlast Werte enthält die nicht `"FELD_NAME":""` sind, dann bitte noch den Tab auf "View Source" umschalten - alles markieren und hier reinpacken... 

Idealerweise für jede Checkbox und die Eingabefelder die Du setzen kannst getrennt (also immer nur ein Wert modifizieren)...

**Comment by patricknitsch** [comment]
Ich denke ich habe da was. Unter Anweisung kann ich arbeiten :)

Schau mal ob dir das ausreicht. Habe auch die Oberfläche mit drauf, damit du die einzelnen Variablen besser zuordnen kannst. 

Wenn du noch etwas brauchst, kannst du gerne bescheid geben.

![image](https://github.com/marq24/ha-senec-v3/assets/114565561/828d0908-dba4-499e-870e-37ff07e5fb16)

**Comment by marq24** [comment]
nee - leider nein - Du guckst Dir gerade die Antwort an - dort stehen dann eben die Wert VOM Senec zu DIR an... 

Du musst im "Nutzdaten" Tab suchen....

**Comment by patricknitsch** [comment]
Neuer Versuch...

![image](https://github.com/marq24/ha-senec-v3/assets/114565561/21e7a639-ea07-4025-8d46-f875b8612cdf)

**Comment by patricknitsch** [comment]
![image](https://github.com/marq24/ha-senec-v3/assets/114565561/f2d05a94-0605-483c-be70-65faa663a453)

**Comment by marq24** [comment]
... damit kann ich wohl was anfangen... -> kannst Du das nochmal mit werten für Stunde/Minute machen?

**Comment by patricknitsch** [comment]
Gerne. Diesmal für beide Kontakte

Kontakt 1:
![image](https://github.com/marq24/ha-senec-v3/assets/114565561/993d2649-8f20-44f0-8c2e-a92ecf5bb289)

Kontakt 2:
![image](https://github.com/marq24/ha-senec-v3/assets/114565561/c4dcef19-b139-43c3-970e-3e335c215fd2)

**Comment by marq24** [comment]
Ich habe noch einen Wunsch - könntest du bitte bei einem Request mal "Quelle Anzeigen drücken und den Text der dann angezeigt wir mit der Maus COPY & PASTEN? - Danke
![image](https://github.com/marq24/ha-senec-v3/assets/8012359/de12b0d1-c095-4f41-bb95-d73464fd9fc7)

**Comment by patricknitsch** [comment]
{"ENERGY":{"ZERO_EXPORT":""},"SOCKETS":{"ENABLE":"","USE_TIME":"","FORCE_ON":"[\"u8_00\",\"\"]","TIME_REM":"","POWER_ON":"","UPPER_LIMIT":"","LOWER_LIMIT":"","TIME_LIMIT":"","POWER_ON_TIME":"","PRIORITY":"","SWITCH_ON_HOUR":"","SWITCH_ON_MINUTE":"","NUMBER_OF_SOCKETS":"","ALREADY_SWITCHED":""}}

**Comment by marq24** [comment]
"Ja iss denn heut scho' Weihnachten?"

**Comment by patricknitsch** [comment]
Das ist bei dem trostlosen Wetter da draußen definitiv wie Weihnachten. Absolut geil!! Funktioniert alles. Dafür werde ich dir für deine Mühen zu Weihnachten einen Kaffee spendieren :)
