### ISSUE TITLE
Failed to setup after the last update

### ISSUE THREAD

**Issue by Disincentivato** [marq24/ha-senec-v3#74]
![image](https://github.com/marq24/ha-senec-v3/assets/90531670/95e595d2-cb37-40b6-b8c0-1b4f1c9ba25c)

After the last update 2024.0.5 it doesn't work anymore. Thank you.
I go back to the 2024.0.1 and all seems ok. No problem with the webapi.

**Comment by jc2308** [comment]
i have the same problem.

**Comment by marq24** [comment]
please update to 2024.0.6 - sorry for this "last-minute-change-caused-this-bug"... Please close this if the new build solve the issue for you...

**Comment by Disincentivato** [comment]
thanks @marq24 !! Works perfect.
