### ISSUE TITLE
my WebAPI configuration doesent work [multi device scenario]

### ISSUE THREAD

**Issue by ilgio** [marq24/ha-senec-v3#82]
<img width="902" alt="Screenshot 2024-03-08 alle 11 46 16" src="https://github.com/marq24/ha-senec-v3/assets/26309528/71ce3c00-14f4-49f4-8154-1f701fc09106">
<img width="1155" alt="Screenshot 2024-03-08 alle 11 46 40" src="https://github.com/marq24/ha-senec-v3/assets/26309528/1f398376-1427-46c6-98b8-b62af378ccfb">
<img width="1210" alt="Screenshot 2024-03-08 alle 11 46 47" src="https://github.com/marq24/ha-senec-v3/assets/26309528/31e81117-4878-4d0a-918d-5ecf1353c6bf">

webapi entity are unknown

and my app with the same credentials I view value correcly
![WhatsApp Image 2024-03-08 at 11 58 26](https://github.com/marq24/ha-senec-v3/assets/26309528/689b292c-5142-422a-a1ae-3107b43bf5d1)

**Comment by marq24** [comment]
can you please be so kind and provide the debug log?!
https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md

**Comment by ilgio** [comment]
> can you please be so kind and provide the debug log?! https://github.com/marq24/ha-senec-v3/blob/master/docs/HA_DEBUG.md

I sent you an email

**Comment by ilgio** [comment]
Maybe because I have 2 systems connected in cascade, master and slave?
<img width="976" alt="Screenshot 2024-03-08 alle 17 28 20" src="https://github.com/marq24/ha-senec-v3/assets/26309528/7a76817c-a9cc-4156-9e62-5d5dae8055d4">

**Comment by marq24** [comment]
yes - this is "multi" Senec device related... Please remove the WebAPI integration and ReAdd a new one - but this time use "master_plant_id" 0 (and not "autodetect")...

**Comment by ilgio** [comment]
ok, now work, thx

**Comment by matzeeg3** [comment]
i have kind of same issue i am not able to add the slave device. i have running with the master but adding the slave result in an unknown error. may someone can tel me how to add it correctly?

**Comment by marq24** [comment]
con you please be so kind and provide DEBUG log output - TIA

**Comment by matzeeg3** [comment]
hi sorry for late response.
i try to add "anlagen:id 1" becase this is my master and i recive the following output:
`homeassistant  | 2024-06-26 10:39:58.786 DEBUG (MainThread) [custom_components.senec.pysenec_ha] ***** APP-API: app_update_tech_data(self) ********
homeassistant  | 2024-06-26 10:39:58.786 DEBUG (MainThread) [custom_components.senec.pysenec_ha] ***** APP-API: app_update_tech_data(self) ********
homeassistant  | 2024-06-26 10:39:58.786 DEBUG (MainThread) [custom_components.senec.pysenec_ha] ***** APP-API: app_authenticate(self) ********
homeassistant  | 2024-06-26 10:39:58.898 DEBUG (MainThread) [custom_components.senec.pysenec_ha] APP-API: response:{'token': 'xxxx', 'refreshToken': ''}
homeassistant  | 2024-06-26 10:39:58.898 DEBUG (MainThread) [custom_components.senec.pysenec_ha] ***** APP-API: get_master_plant_id(self) ********
homeassistant  | 2024-06-26 10:39:59.229 DEBUG (MainThread) [custom_components.senec.pysenec_ha] APP-API response: [{'id': '59226', 'steuereinheitnummer': 'xxxx', 'gehaeusenummer': 'xxx', 'strasse': 'xxx', 'hausnummer': 'x', 'postleitzahl': 'xxxx', 'ort': 'xxxx', 'zeitzone': 'Europe/Berlin', 'wallboxIds': [], 'systemType': 'V2'}]
homeassistant  | 2024-06-26 10:39:59.229 WARNING (MainThread) [custom_components.senec.pysenec_ha] Index: 1 not available in array data: '[{'id': '59226', 'steuereinheitnummer': 'xxxx', 'gehaeusenummer': 'xxx', 'strasse': 'xxxx', 'hausnummer': 'xxx', 'postleitzahl': 'xxxx', 'ort': 'xxx', 'zeitzone': 'Europe/Berlin', 'wallboxIds': [], 'systemType': 'V2'}]'
homeassistant  | 2024-06-26 10:39:59.230 ERROR (MainThread) [custom_components.senec.pysenec_ha] APP-API: could not fetch master plant id (aka 'anlagen:id')
homeassistant  | 2024-06-26 10:39:59.230 DEBUG (MainThread) [custom_components.senec.pysenec_ha] ***** APP-API: app_update_tech_data(self) ********
homeassistant  | 2024-06-26 10:39:59.230 ERROR (MainThread) [aiohttp.server] Error handling request`
For Privacy reasons i removed the serial numbers and so on....
if i open up the api with the url:
https://mein-senec.de/endkunde/api/context/getAnlageBasedNavigationViewModel?anlageNummer=1
i recive data and "master":true
if i use
https://mein-senec.de/endkunde/api/context/getAnlageBasedNavigationViewModel?anlageNummer=0
i revice the data and master:false

**Comment by marq24** [comment]
can you please be so kind and send me the RESPONSE JSON's from both of the requests?

- getAnlageBasedNavigationViewModel?anlageNummer=1 

and

- getAnlageBasedNavigationViewModel?anlageNummer=0

[via eMail]...

**Comment by matzeeg3** [comment]
sure what is the base url?

**Comment by marq24** [comment]
well - https://mein-senec.de/endkunde/api/context/

**Comment by matzeeg3** [comment]
> well - https://mein-senec.de/endkunde/api/context/

oh got damm i posted the link befor ^^ sorry for that to mutch work around.
i send you the output. thanks in advanced
- matze

**Comment by marq24** [comment]
So I do believe I have now finally understood your initial question Matze...

There is __no__ way to add a __SLAVE__ device to HA... When you have connected the Master (the Autodetect 'should' work) with HA, the data/values that are returned from these endpoints include also the values from the Slave (at least that's the overall/general assumption)... 

It's correct, that (currently) you can not add 'anlagen:nummer 1' -> since the response from SENEC from the ´anlagen´ endpoint only include a single unit -> this is IMHO a error in the API from SENEC - when you have master & slave then the request for Anage__n__ should return ALL systems - not only one... 

When you use "autodetect" mode, the code should find the correct master (@ analgen nummer 1)

**Comment by matzeeg3** [comment]
hi thanks for analyzing this.
so at the moment i don´t have the ability to get the value for each batteriy like %-Loaded and KWH in and out i only recive what the masterunit provide. i hoped with this solution i am able to see the kwh in and out from each battery and not a summerd of both. thanks for you help :)

**Comment by marq24** [comment]
you can get data via the LAN-based integration - most of the data is there - per IP of each of your devices - but not the statistic data... see #4

**Comment by matzeeg3** [comment]
yes i know i used this before i choose to switch to the cloud solution. the historical data is gone so it is not nice to use this anymore....
