### ISSUE TITLE
SOCKET Sensors - what the heck is that?

### ISSUE THREAD

**Issue by sbetti1973** [marq24/ha-senec-v3#86]
wath is the realy function of "senec_master_sockets_1_upper_limit" or
"senec_master_sockets_1_automatic_enable"

thank you

**Comment by marq24** [comment]
These are the sensors that have been added if you have bought the technic-package -> https://github.com/marq24/ha-senec-v3/issues/63 [the names of the sensor's are indeed a bit difficult to understand - but with the translations it should match the names of the original Senec GUI

**Comment by sbetti1973** [comment]
thank you for fast replay, i not have a technic-package, i not have a user/password for this, the installator not give me, you know if it's possible to have it?

**Comment by marq24** [comment]
well - you have to purchase it from SENEC...
